apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata: 
  name: deploy-simple-kubectl-task
spec:
  inputs: 
    resources: 
    - name: git-source
      type: git
  steps:
  - name: delete-previous
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args: 
    - 'delete'
    - '-f'
    - '/workspace/git-source/config'
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args: 
    - 'create'
    - '-f'
    - '/workspace/git-source/config'