apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata: 
  name: deploy-simple-kubectl-task
spec:
  inputs: 
    resources: 
    - name: git-source
      type: git
    - name: image-out
      type: image
  steps:
  - name: modify-yaml
    image: alpine
    command: ['sed']
    args: 
    - '-i.bak'
    - 's!image:.*!image: ${inputs.resources.image-out.url}!g'
    - '/workspace/git-source/config/deployment.yaml'
  - name: check
    image: alpine
    command: ['cat']
    args: 
    - '/workspace/git-source/config/deployment.yaml'
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args: 
    - 'apply'
    - '-f'
    - '/workspace/git-source/config'
    