apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata: 
  name: print-endpoint-task
spec:
  inputs: 
    resources: 
    - name: git-source
      type: git
  steps:
  - name: print-endpoint
    image: ubuntu
    command: [/bin/bash]
    args: ['-c', 'if [ -f /workspace/git-source/echo.sh ]; then /workspace/git-source/echo.sh; fi']
