apiVersion: v1
kind: Secret
metadata:
  name: github-repo-access-secret
  annotations:
    build.knative.dev/git-0: https://github.ibm.com # CHANGE IF GITHUB.COM
type: kubernetes.io/basic-auth
stringData:
  username: does_not_matter
  password: YOUR_GITHUB_ACCESS_TOKEN

---

apiVersion: v1
kind: ServiceAccount
metadata:
  #CHANGE THIS IF USING DIFFERENT SERVICE ACCOUNT?
  name: default
secrets:
  - name: github-repo-access-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  accessToken: YOUR_GITHUB_ACCESS_TOKEN
  secretToken: SOME_RANDOM_STRING_HERE

---

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: github-event-source-sample
spec:
  eventTypes:
    - push
    - pull_request
  ownerAndRepository: Jessica-McCreery/sample
  accessToken:
    secretKeyRef:
      name: github-secret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: github-secret
      key: secretToken
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: github-event-pipeline

