apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-git-source-{{.SHORTID}}
spec:
  type: git
  params:
  - name: revision
    value: {{.ID}}
  - name: url
    value: {{.URL}}

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-image-resource-{{.SHORTID}}
spec:
  type: image
  params:
  - name: url
    # In the examples below {{.NAME}} will be replaced for you but the username must be set yourself.

    # To use the public Docker registry:
    # value: docker.io/<Your username>/{{.NAME}}
  
    # To use `latest` as the tag:
    # value: host.docker.internal:5000/knative/{{.NAME}}

    # To use the commit ID as the tag:
    value: host.docker.internal:5000/knative/{{.NAME}}:{{.SHORTID}}